local settings = {
  header = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Header",
    margin = 5,
    content = {
      "                                          ▄▄                     ",
      " ███▀▀▀███                  ▀████▀   ▀███▀ ██                    ",
      " █▀   ███                     ▀██     ▄█                         ",
      " ▀   ███   ▄▄█▀██▀████████▄    ██▄   ▄█  ▀███ ▀████████▄█████▄   ",
      "    ███   ▄█▀   ██ ██    ██     ██▄  █▀    ██   ██    ██    ██   ",
      "   ███   ▄██▀▀▀▀▀▀ ██    ██     ▀██ █▀     ██   ██    ██    ██   ",
      "  ███   ▄███▄    ▄ ██    ██      ▄██▄      ██   ██    ██    ██   ",
      " █████████ ▀█████▀████  ████▄     ██     ▄████▄████  ████  ████▄ ",
      "",
    },
    highlight = "String",
    oldfiles_amount = 0,
  },
  body = {
    type = "mapping",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Quick Actions",
    margin = 5,
    content = {
      { "󰈞 Find File", "Telescope find_files", "<leader>ff" },
      { "󰊄 Find Word", "Telescope live_grep", "<leader>fg" },
      { "󰋚 Recent", "Telescope oldfiles", "<leader>fr" },
      { "󱋣 Projects", "Telescope projects", "<leader>fp" },
      { "󰙅 File Tree", "NvimTreeToggle", "<leader>e" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },

  footer = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Commands Reference",
    margin = 5,
    content = {
      "Navigation",
      "----------------------------------------",
      "h/j/k/l - Left/Down/Up/Right",
      "w/b     - Next/previous word",
      "0/$     - Start/End of line",
      "gg/G    - First/Last line",
      "''      - Jump to last position",
      "CTRL-o/i- Jump backward/forward",
      "",
      "Editing",
      "----------------------------------------",
      "i/a     - Insert before/after cursor",
      "o/O     - Insert line below/above",
      "dd/yy   - Delete/Yank line",
      "p/P     - Paste after/before",
      "u/CTRL-r- Undo/Redo",
      "ciw     - Change inner word",
      "cc      - Change entire line",
      "",
      "Tabs & Windows",
      "----------------------------------------",
      "<leader>tn/tq - New/Close tab",
      "<leader>th/tl - Previous/Next tab",
      "CTRL-w v/s   - Split vertical/horizontal",
      "CTRL-w h/j/k/l - Navigate splits",
      "",
      "LSP & Search",
      "----------------------------------------",
      "gd         - Go to definition",
      "K          - Show hover info",
      "<leader>rn - Rename symbol",
      "<leader>ca - Code actions",
      "/pattern   - Search forward",
      "?pattern   - Search backward",
      "n/N        - Next/Previous match",
      "",
      "File Operations",
      "----------------------------------------",
      ":w/:wq/:q!   - Save/Save&Quit/Force quit",
      ":e <file>    - Edit file",
      ":cd <dir>    - Change directory (per tab)",
      ":Tree        - Toggle file tree",
    },
    highlight = "Number",
    default_color = "",
    oldfiles_amount = 0,
  },

  options = {
    mapping_keys = true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = true,
    paddings = { 1, 3, 3, 0 },
  },

  mappings = {
    execute_command = "<CR>",
    open_file = "o",
    open_file_split = "<c-o>",
    open_section = "<TAB>",
    open_help = "?",
  },

  colors = {
    background = "#1f2227",
    folded_section = "#56b6c2",
  },

  parts = { "header", "body", "footer" },
}

return settings
